environment: {}
parameters: {}
packages:
  - name: godot
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: version
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: gdscript
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
      - name: test
        binary: false
        main: ''
        runtime: 'python:default'
        web: true
        parameters:
          code: "print(Engine.get_version_info())"
        environment: {}
        annotations: {}
        limits: {}
