sitename: Tumeo Space
title: GDScript Playground
description: Try a script right now! Desktop or mobile web browser.
author: William Tumeo
siteurl: https://gd.tumeo.space/
baseurl: /

repourl: https://github.com/williamd1k0/gdscript-playground
twitter: "@tumeo_"

function_url: https://faas-nyc1-2ef2e6cc.doserverless.co/api/v1/web/fn-a614ecdd-5af6-46c4-b511-d3f7c9e3f191/

version_function:
  url: godot/version
  token: Ok36iwwCb7eERn4
gdscript_function:
  url: godot/gdscript
  token: Yz3k5YFGir5ec88

rentry_function:
  url: share/rentry
  token: Ka7WuJGcMIly9Dr

gist_function:
  url: share/gist
  token: Zp7kI6inEK1lhd4

ads_enabled: true
custom_ads_enabled: true
adsbygoogle_enabled: false
