sitename: Tumeo Space
title: GDScript Playground
description: Try a script right now! Desktop or mobile web browser.
author: William Tumeo
siteurl: https://gd.tumeo.space/
baseurl: /

repourl: https://github.com/williamd1k0/gdscript-playground
twitter: "@tumeo_"

function_url: https://faas-nyc1-2ef2e6cc.doserverless.co/api/v1/web/fn-f1a44419-c8a0-4cf5-b9af-d12c7a947ca8/

version_function:
  url: godot/version
  token: Va7SERobvyMAkg9
gdscript_function:
  url: godot/gdscript
  token: Op2VrNDf6aiY8Jv

rentry_function:
  url: share/rentry
  token: Qy4TKS1Psz1OPct
gist_function:
  url: share/gist
  token: Ri1bVMVzSmG30h4

ads_enabled: true
custom_ads_enabled: true
adsbygoogle_enabled: false
